import type { Metadata } from "next";
import "./index.css";
import { ApolloWrapper } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloWrapper>
      <html lang="ja">
        <body>{children}</body>
      </html>
    </ApolloWrapper>
  );
}
