import type { Metadata } from "next";
import "./index.css";
import { ApolloWrapper } from "./providers";
import { ToastProvider, ErrorBoundary } from "./_components/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloWrapper>
      <html lang="ja">
        <body>
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
          <ToastProvider />
        </body>
      </html>
    </ApolloWrapper>
  );
}
